language: ruby
rvm:
  - 1.9.2
  - 1.9.3
gemfile:
  - gemfiles/activerecord_3_0.gemfile
  - gemfiles/activerecord_3_1.gemfile
  - gemfiles/activerecord_3_2.gemfile
  - gemfiles/activerecord_4_0.gemfile
script: rspec
matrix:
   exclude:
      - rvm: 1.9.2
        gemfile: gemfiles/activerecord_4_0.gemfile
