name: Tests
on: [push]

jobs:
  ruby:
    name: Rspec
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7]
        activerecord: ["5.0", "5.1", "5.2", "6.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Set ActiveRecord Version
        env:
          AR_VERSION: ${{ matrix.activerecord }}
        run: echo "gem 'activerecord', '~> $AR_VERSION'" >> Gemfile
      - name: Install Sqlite
        run: sudo apt-get install libsqlite3-dev
      - name: Bundle
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Tests
        run: bundle exec rake spec
